# Generated by Django 2.2.13 on 2020-06-13 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_auto_20200411_0038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FitnessPlan',
        ),
    ]
